name: clean_architecture
description: Clean Architecture Boilerplate
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # cupertino_icons: ^1.0.8
  # Equality
  equatable: ^2.0.5
  # Dependency Injector
  get_it: ^7.7.0
  # Network
  connectivity_plus: ^6.0.3
  internet_connection_checker: ^2.0.0
  http_parser: ^4.0.2
  dio: ^5.6.0
  alice: ^0.4.2
  awesome_dio_interceptor: ^1.2.0
  # Router
  auto_route: ^9.2.0
  # Offline
  shared_preferences: ^2.3.2
  # State Management
  flutter_bloc: ^8.1.6
  flutter_hooks: ^0.20.5
  # Image Picker
  image_picker: ^1.1.2
  # Animation
  flutter_sliding_toast: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

    - family: AppIcon
      fonts:
        - asset: assets/icons/AppIcon.ttf
